require("dotenv").config();

module.exports = {
  gigwaServers: JSON.parse(process.env.GIGWA_SERVERS || "{}"),
  germinateServer: process.env.GERMINATE_SERVER,
  genolinkServer: process.env.GENOLINK_SERVER,
  genesysServer: process.env.GENESYS_SERVER,
  genolinkServerPort: process.env.GENOLINK_SERVER_PORT || 4000,
  sampStatMapping: {
    100: "Wild",
    110: "Natural",
    120: "Semi-natural/wild",
    130: "Semi-natural/sown",
    200: "Weedy",
    300: "Traditional cultivar/Landrace",
    400: "Breeding/Research Material",
    410: "Breeders Line",
    411: "Synthetic population",
    412: "Hybrid",
    413: "Founder stock/base population",
    414: "Inbred line",
    415: "Segregating population",
    416: "Clonal selection",
    420: "Genetic stock",
    421: "Mutant",
    422: "Cytogenetic stocks",
    423: "Other genetic stocks",
    500: "Advanced/improved cultivar",
    600: "GMO",
    999: "Other",
  },
};
